### PR TITLE
ax_int128.m4: new macro AX_HAVE_INT128

### PR DESCRIPTION
**Pull request by rrthomas**

### CODE REVIEW

**Comment by petk** [comment]
Thank you @rrthomas for the new macro.

**Comment by peti** [comment]
@petk, please  don't merge PRs that fail the test suite.

**Comment by petk** [comment]
I see it fails yes. Sorry for the missed check. I can take a look at it what is exiting with error...

**Comment by peti** [comment]
The fix is trivial. I pushed it in fce06d3b8d02dcc50a79c9efb21a3ae91fb041f7.

**Comment by petk** [comment]
Thank you @peti

**Pull request merged**
